//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.27 at 12:08:54 AM CET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.newzbin.com/DTD/2003/nzb", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.model;
