server.port=8080
logging.level.io.milton=DEBUG
logging.level.org.webdav=DEBUG
logging.level.org.example=INFO

# Usenet Configuration
usenet.server=YOUR_USENET_SERVER
usenet.port=119
usenet.username=YOUR_USENET_USERNAME
usenet.password=YOUR_USENET_PASSWORD


# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/nzb
spring.datasource.username=nzb
spring.datasource.password=nzb
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
