//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.27 at 12:08:54 AM CET 
//


package com.newzbin.dtd._2003.nzb;

import jakarta.xml.bind.annotation.XmlRegistry;
import org.model.Nzb;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.newzbin.dtd._2003.nzb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.newzbin.dtd._2003.nzb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Nzb }
     * 
     */
    public Nzb createNzb() {
        return new Nzb();
    }

    /**
     * Create an instance of {@link Nzb.File }
     * 
     */
    public Nzb.File createNzbFile() {
        return new Nzb.File();
    }

    /**
     * Create an instance of {@link Nzb.File.Segments }
     * 
     */
    public Nzb.File.Segments createNzbFileSegments() {
        return new Nzb.File.Segments();
    }

    /**
     * Create an instance of {@link Nzb.Head }
     * 
     */
    public Nzb.Head createNzbHead() {
        return new Nzb.Head();
    }

    /**
     * Create an instance of {@link Nzb.File.Groups }
     * 
     */
    public Nzb.File.Groups createNzbFileGroups() {
        return new Nzb.File.Groups();
    }

    /**
     * Create an instance of {@link Nzb.File.Segments.Segment }
     * 
     */
    public Nzb.File.Segments.Segment createNzbFileSegmentsSegment() {
        return new Nzb.File.Segments.Segment();
    }

    /**
     * Create an instance of {@link Nzb.Head.Meta }
     * 
     */
    public Nzb.Head.Meta createNzbHeadMeta() {
        return new Nzb.Head.Meta();
    }

}
